apiVersion: v1
kind: Secret
metadata:
  name: mern-app-secrets
  namespace: mern-app
stringData: # Changed from data to stringData for direct string input
  JWT_SECRET: "${JWT_SECRET}"
  MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
  MONGODB_USERNAME: "${MONGODB_USERNAME}"
  MONGO_URI: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb-service:27017/${MONGODB_DATABASE}?authSource=admin"
# Opaque is the default type and can be omitted
