apiVersion: v1
kind: ConfigMap
metadata:
  name: mern-app-config
  namespace: mern-app
data:
  NODE_ENV: "production"
  PORT: "5000"
  FRONTEND_URL: "${K8S_FRONTEND_URL}"
  VITE_BACKEND_URL: "${K8S_BACKEND_URL}"
  MONGODB_DATABASE: "mern-auth"
