apiVersion: v1
kind: Secret
metadata:
  name: mern-app-secrets
  namespace: mern-app
type: Opaque
stringData:
  JWT_SECRET: "your_jwt_secret_key"
  MONGODB_USERNAME: "admin"
  MONGODB_PASSWORD: "secure_password_here"
  MONGO_URI: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${KUBERNETES_MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin"
